"""Standalone HTML rendering of stability-analysis reports.

The command-line interface serialises each analysis to a plain dictionary;
this module turns those dictionaries into a single self-contained HTML
document (inline CSS, no external assets) that can be reviewed in a browser
or attached to a regulatory submission as a human-readable record.

Only the Python standard library is used.
"""

from __future__ import annotations

import html
from typing import Any, List, Mapping

_CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Helvetica, Arial, sans-serif;
  margin: 0 auto;
  max-width: 60rem;
  padding: 2rem 1.5rem;
  background: #f7f7f9;
  color: #1c1c1e;
  line-height: 1.5;
}
h1 { font-size: 1.6rem; margin: 0 0 0.25rem; }
h2 { font-size: 1.15rem; margin: 2rem 0 0.5rem; }
p.subtitle { color: #6b6b70; margin: 0 0 1.5rem; }
table {
  border-collapse: collapse;
  width: 100%;
  margin: 0.5rem 0 1rem;
  background: #ffffff;
  font-size: 0.95rem;
}
caption { text-align: left; font-weight: 600; padding: 0.25rem 0 0.5rem; }
th, td { border: 1px solid #d5d5da; padding: 0.4rem 0.6rem; text-align: right; }
th:first-child, td:first-child { text-align: left; }
thead th { background: #ececf1; }
.pass { color: #2f7d32; font-weight: 600; }
.fail { color: #b3261e; font-weight: 600; }
footer { margin-top: 2rem; color: #8a8a90; font-size: 0.8rem; }
"""



def _e(value: Any) -> str:
    """HTML-escape *value* for safe insertion into the document."""
    return html.escape(str(value))


def render_html_report(report: Mapping[str, Any]) -> str:
    """Render a CLI report dictionary as a standalone HTML document.

    Both report shapes produced by the command-line interface are supported:
    the ICH Q1E report (key ``batches``) and the Arrhenius report (key
    ``arrhenius``).  A :class:`ValueError` is raised for anything else.
    """
    if "batches" in report:
        body = _render_q1e(report)
        title = "ICH Q1E stability analysis"
    elif "arrhenius" in report:
        body = _render_arrhenius(report)
        title = "Arrhenius stability extrapolation"
    else:
        raise ValueError("unrecognised stability report structure")

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{_e(title)}</title>\n<style>{_CSS}</style>\n</head>\n"
        f"<body>\n{body}\n"
        '<footer>Generated by stability-shelf-life.</footer>\n'
        "</body>\n</html>\n"
    )


def _models_table(entry: Mapping[str, Any]) -> str:
    """Render the per-batch kinetic model fits as a table."""
    rows = "".join(
        "<tr>"
        f"<td>{_e(model['model'])}</td>"
        f"<td>{_e(model['rate'])}</td>"
        f"<td>{_e(model['rate_unit'])}</td>"
        f"<td>{_e(model['initial_potency'])}</td>"
        f"<td>{_e(model['r_squared'])}</td>"
        "</tr>"
        for model in entry["models"]
    )
    return (
        "<table>"
        f"<caption>Model fits ({_e(entry['n_points'])} time points)</caption>"
        "<thead><tr>"
        "<th>Model</th><th>Rate</th><th>Unit</th>"
        "<th>Initial potency (%)</th><th>R&#178;</th>"
        "</tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def _slope_table(tests: List[Mapping[str, Any]]) -> str:
    """Render the between-batch slope-comparison F tests as a table."""
    rows = []
    for test in tests:
        f_statistic = test.get("f_statistic")
        f_text = "inf" if f_statistic is None else str(f_statistic)
        verdict = (
            "differ significantly"
            if test["slopes_differ"]
            else "do not differ significantly"
        )
        css_class = "fail" if test["slopes_differ"] else "pass"
        rows.append(
            "<tr>"
            f"<td>{_e(test['model'])}</td>"
            f"<td>{_e(', '.join(test['batch_ids']))}</td>"
            f"<td>{_e(f_text)}</td>"
            f"<td>{_e(test['df_between'])}, {_e(test['df_within'])}</td>"
            f"<td>{_e(test['p_value'])}</td>"
            f'<td class="{css_class}">{verdict}</td>'
            "</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Model</th><th>Batches</th><th>F</th><th>df</th>"
        "<th>p-value</th><th>Conclusion</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _render_q1e(report: Mapping[str, Any]) -> str:
    """Render the body of an ICH Q1E report."""
    sections: List[str] = [
        "<h1>ICH Q1E stability analysis</h1>",
        f'<p class="subtitle">Specification limit: {_e(report["limit"])}%</p>',
    ]

    for entry in report.get("batches", []):
        if entry.get("shelf_life_months") is None:
            verdict = (
                '<p class="fail">No degradation detected; '
                "shelf life is not estimable.</p>"
            )
        else:
            verdict = (
                "<p>Shelf life: "
                f"<strong>{_e(entry['shelf_life_months'])} months</strong> "
                f"(best model: {_e(entry['best_model'])}, one-sided 95% "
                f"lower bound "
                f"{_e(entry['shelf_life_lower_95_months'])} months).</p>"
            )
        sections.append(
            f'<h2>Batch {_e(entry["batch_id"])}</h2>'
            + _models_table(entry)
            + verdict
        )

    slope_tests = report.get("slope_difference") or []
    if slope_tests:
        sections.append(
            "<h2>Slope comparison between batches</h2>"
            "<p>Extra-sum-of-squares F test for equality of degradation "
            "slopes. ICH Q1E permits pooling only when the slopes do not "
            "differ significantly.</p>"
            + _slope_table(slope_tests)
        )

    return "\n".join(sections)


def _render_arrhenius(report: Mapping[str, Any]) -> str:
    """Render the body of an Arrhenius report."""
    rows = "".join(
        "<tr>"
        f"<td>{_e(rate['temperature_c'])}</td>"
        f"<td>{_e(rate['rate_1_per_month'])}</td>"
        f"<td>{_e(rate['r_squared'])}</td>"
        "</tr>"
        for rate in report.get("rates", [])
    )
    rates_table = (
        "<table><caption>Degradation rate at each temperature</caption>"
        "<thead><tr><th>Temperature (&#176;C)</th><th>Rate (1/month)</th>"
        "<th>R&#178;</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )

    arrhenius = report.get("arrhenius", {})
    arrhenius_table = (
        "<table><caption>Arrhenius fit</caption><tbody>"
        "<tr><td>Activation energy (kJ/mol)</td>"
        f"<td>{_e(arrhenius.get('activation_energy_kj_mol'))}</td></tr>"
        "<tr><td>Pre-exponential factor</td>"
        f"<td>{_e(arrhenius.get('pre_exponential_factor'))}</td></tr>"
        f"<tr><td>R&#178;</td><td>{_e(arrhenius.get('r_squared'))}</td></tr>"
        "</tbody></table>"
    )

    prediction = report.get("prediction", {})
    shelf = prediction.get("shelf_life_months")
    shelf_text = "not estimable" if shelf is None else f"{_e(shelf)} months"
    prediction_table = (
        "<table><caption>Prediction</caption><tbody>"
        "<tr><td>Storage temperature (&#176;C)</td>"
        f"<td>{_e(prediction.get('storage_temperature_c'))}</td></tr>"
        "<tr><td>Predicted rate (1/month)</td>"
        f"<td>{_e(prediction.get('rate_1_per_month'))}</td></tr>"
        f"<tr><td>Predicted shelf life</td><td>{shelf_text}</td></tr>"
        "</tbody></table>"
    )

    return "\n".join(
        [
            "<h1>Arrhenius stability extrapolation</h1>",
            rates_table,
            arrhenius_table,
            prediction_table,
        ]
    )
